name: Run tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DISPLAY: :1

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        echo "Display: $DISPLAY"
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install -r requirements_all.txt

    - name: Setup xvfb for screen 0
      run: Xvfb :1 -screen 0 3200x2400x8
    - name: Test with pytest
      env:
        DISPLAY: :1
      run: |
        pytest tests/test_builder.py
        pytest tests/test_examples.py
        pytest tests/test_models.py
        pytest tests/test_optas_utils.py
        pytest tests/test_optimization.py
        pytest tests/test_solver.py
        pytest tests/test_spatialmath.py
        pytest tests/test_sx_container.py
    - name: Tear down xvfb
      run: killall Xvfb
